# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='verified',
            field=models.NullBooleanField(default=False),
        ),
    ]
