# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_auto_20171102_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='main_image_url',
            field=models.URLField(max_length=1000),
        ),
    ]
